// Code generated by protoc-gen-go.
// source: coffee.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	coffee.proto

It has these top-level messages:
	CoffeeRequest
	CoffeeResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CoffeeRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CoffeeRequest) Reset()                    { *m = CoffeeRequest{} }
func (m *CoffeeRequest) String() string            { return proto1.CompactTextString(m) }
func (*CoffeeRequest) ProtoMessage()               {}
func (*CoffeeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CoffeeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CoffeeResponse struct {
	Price   int32  `protobuf:"varint,1,opt,name=price" json:"price,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *CoffeeResponse) Reset()                    { *m = CoffeeResponse{} }
func (m *CoffeeResponse) String() string            { return proto1.CompactTextString(m) }
func (*CoffeeResponse) ProtoMessage()               {}
func (*CoffeeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CoffeeResponse) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CoffeeResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CoffeeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*CoffeeRequest)(nil), "Coffee.CoffeeRequest")
	proto1.RegisterType((*CoffeeResponse)(nil), "Coffee.CoffeeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Coffee service

type CoffeeClient interface {
	Order(ctx context.Context, in *CoffeeRequest, opts ...grpc.CallOption) (*CoffeeResponse, error)
}

type coffeeClient struct {
	cc *grpc.ClientConn
}

func NewCoffeeClient(cc *grpc.ClientConn) CoffeeClient {
	return &coffeeClient{cc}
}

func (c *coffeeClient) Order(ctx context.Context, in *CoffeeRequest, opts ...grpc.CallOption) (*CoffeeResponse, error) {
	out := new(CoffeeResponse)
	err := grpc.Invoke(ctx, "/Coffee.Coffee/Order", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Coffee service

type CoffeeServer interface {
	Order(context.Context, *CoffeeRequest) (*CoffeeResponse, error)
}

func RegisterCoffeeServer(s *grpc.Server, srv CoffeeServer) {
	s.RegisterService(&_Coffee_serviceDesc, srv)
}

func _Coffee_Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoffeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeServer).Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Coffee.Coffee/Order",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeServer).Order(ctx, req.(*CoffeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coffee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Coffee.Coffee",
	HandlerType: (*CoffeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Order",
			Handler:    _Coffee_Order_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coffee.proto",
}

func init() { proto1.RegisterFile("coffee.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0x4f, 0x4b,
	0x4b, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x73, 0x06, 0xf3, 0x94, 0x94, 0xb9,
	0x78, 0x21, 0xac, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4,
	0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x29, 0x84, 0x8b, 0x0f, 0xa6,
	0xa8, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x84, 0x8b, 0xb5, 0xa0, 0x28, 0x33, 0x19, 0xa2,
	0x8c, 0x35, 0x08, 0xc2, 0x81, 0xeb, 0x65, 0x42, 0xe8, 0x15, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x06, 0x0b, 0xc3, 0xb8, 0x46, 0x4e, 0x5c, 0x50, 0x47, 0x08,
	0x59, 0x70, 0xb1, 0xfa, 0x17, 0xa5, 0xa4, 0x16, 0x09, 0x89, 0xea, 0x41, 0x44, 0xf4, 0x50, 0xdc,
	0x24, 0x25, 0x86, 0x2e, 0x0c, 0x71, 0x85, 0x12, 0x83, 0x93, 0x16, 0x97, 0x62, 0x72, 0x7e, 0xae,
	0x5e, 0x49, 0x62, 0x76, 0x69, 0x71, 0x6a, 0x6e, 0x52, 0xa2, 0x5e, 0x7a, 0x51, 0x41, 0xb2, 0x5e,
	0x62, 0x5e, 0x4a, 0x51, 0x7e, 0x66, 0x0a, 0xc4, 0xab, 0xc5, 0x51, 0xac, 0x60, 0x3a, 0x89, 0x0d,
	0x4c, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x3d, 0xfe, 0x8c, 0x09, 0x01, 0x00, 0x00,
}
